#!/usr/bin/python3
# -*- coding: utf-8 -*-
TESTING = False
DEBUG = True

SECRET_KEY = ''
SECURITY_PASSWORD_SALT = ''

SQLALCHEMY_DATABASE_URI = ''

MAIL_SERVER = 'smtp.mailgun.org'
MAIL_PORT = 2525
# MAIL_USE_TLS = True
# MAIL_USE_SSL = True
MAIL_USERNAME = ''
MAIL_PASSWORD = ''

REDIS_URL = "redis://localhost:6379/0"

SECURITY_SEND_REGISTER_EMAIL = True
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = True
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = True
SECURITY_SEND_PASSWORD_RESET_EMAIL = True
